#!/usr/bin/env python3
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

PHRASES = [
    "AI-generated",
    "AI generated",
    "auto-generated",
    "autogenerated",
    "This is an experiment",
    "experimental project",
    "we cannot guarantee",
    "may be incomplete",
    "not financial advice",
    "not legal advice",
    "coming soon",
    "under construction",
    "we try to",
    "we aim to",
    "beta version",
    "in beta",
]

def main():
    matches = []
    for p in sorted(ROOT.rglob("*.html")):
        if ".git" in p.parts:
            continue
        try:
            content = p.read_text(encoding="utf-8")
        except Exception:
            continue
        lines = content.splitlines()
        for i, line in enumerate(lines, 1):
            for phrase in PHRASES:
                if phrase.lower() in line.lower():
                    matches.append((p.relative_to(ROOT), i, phrase, line.strip()[:140]))

    if not matches:
        print("No matches found. Site is clean.")
        return

    print(f"\n=== FOUND {len(matches)} MATCHES ===\n")
    current_file = None
    for f, line_no, phrase, snippet in matches:
        if f != current_file:
            print(f"\n📄 {f}")
            current_file = f
        print(f"   Line {line_no} [{phrase}]")
        print(f"   → {snippet}")

if __name__ == "__main__":
    main()
